import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { auth0 } from "@/lib/auth0";
import "./globals.css";
import { MainNav } from "@/components";
import { FavouritesProvider } from "@/context/FavouritesContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth0.getSession();
  const user = session?.user;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MainNav isAuthenticated={!!user} />
        <FavouritesProvider>
          {children}
        </FavouritesProvider>
      </body>
    </html>
  );
}
