name: CI

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Unit tests
        run: npm run test:unit

      - name: Integration tests
        run: npm run test:integration

  e2e:
    runs-on: ubuntu-latest
    needs: quality

    env:
      NEXT_PUBLIC_BASE_URL: http://localhost:3000
      APP_BASE_URL: http://localhost:3000
      AUTH0_BASE_URL: http://localhost:3000

      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_E2E_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_E2E_CLIENT_SECRET }}
      AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}

      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: npm ci

      - name: Start Next.js
        run: npm run dev &
        
      - name: Wait for app
        run: npx wait-on http://localhost:3000

      - name: Run Cypress
        run: npx cypress run